apiVersion: v1
data:
  color: red
  key: value
immutable: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"color":"red","key":"value"},"immutable":true,"kind":"ConfigMap","metadata":{"annotations":{},"name":"colorcmcli","namespace":"default"}}
  creationTimestamp: "2026-02-14T15:41:49Z"
  name: colorcmcli
  namespace: default
  resourceVersion: "18695"
  uid: 37484786-c334-4a97-8d2f-4bad4203c144
