apiVersion: batch/v1
kind: Job
metadata:
  name: calcpijob
spec:
  completions: 20
  parallelism: 5
  template:
    metadata: {}
    spec:
      containers:
      - command:
        - perl
        - -Mbignum=bpi
        - -wle
        - print bpi(2000)
        image: perl:5.34.0
        name: calcpijob
        resources: {}
      restartPolicy: Never
status: {}
