apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"sleep20","namespace":"default"},"spec":{"completions":20,"parallelism":5,"template":{"metadata":{},"spec":{"containers":[{"command":["sleep","20"],"image":"ubuntu","name":"sleep20","resources":{}}],"restartPolicy":"Never"}}},"status":{}}
  creationTimestamp: "2026-02-14T13:53:42Z"
  generation: 1
  labels:
    batch.kubernetes.io/controller-uid: 46b490c4-958f-4b01-8de6-0214556b9c86
    batch.kubernetes.io/job-name: sleep20
    controller-uid: 46b490c4-958f-4b01-8de6-0214556b9c86
    job-name: sleep20
  name: sleep20
  namespace: default
  resourceVersion: "6279"
  uid: 46b490c4-958f-4b01-8de6-0214556b9c86
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 20
  manualSelector: false
  parallelism: 5
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 46b490c4-958f-4b01-8de6-0214556b9c86
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/controller-uid: 46b490c4-958f-4b01-8de6-0214556b9c86
        batch.kubernetes.io/job-name: sleep20
        controller-uid: 46b490c4-958f-4b01-8de6-0214556b9c86
        job-name: sleep20
    spec:
      containers:
      - command:
        - sleep
        - "20"
        image: ubuntu
        imagePullPolicy: Always
        name: sleep20
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2026-02-14T13:55:19Z"
  conditions:
  - lastProbeTime: "2026-02-14T13:55:19Z"
    lastTransitionTime: "2026-02-14T13:55:19Z"
    message: Reached expected number of succeeded pods
    reason: CompletionsReached
    status: "True"
    type: SuccessCriteriaMet
  - lastProbeTime: "2026-02-14T13:55:19Z"
    lastTransitionTime: "2026-02-14T13:55:19Z"
    message: Reached expected number of succeeded pods
    reason: CompletionsReached
    status: "True"
    type: Complete
  ready: 0
  startTime: "2026-02-14T13:53:42Z"
  succeeded: 20
  terminating: 0
  uncountedTerminatedPods: {}
