apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - command:
    - bash
    - -c
    - env;sleep infinity
    image: ubuntu
    name: ubuntupod
    envFrom:
    - secretRef:
        name: ubuntudevsecret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
