apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - name: nginxpod
    image: nginx
    resources: {}
  - name: ubuntu-sidecar
    image: ubuntu
    args:
    - /bin/sh
    - -c
    - while true; do echo "$(date) - Hello from sidecar"; sleep 5; if [ -f /tmp/crash ]; then exit 1; fi; done
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
