apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginxpdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginxdep
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
