apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupodemptydir
  name: ubuntupodemptydir
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupodemptydir
    resources: {}
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: cache-volume
    emptyDir: {
      medium: Memory
    }
status: {}
