apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxdep
  name: nginxcip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdep
status:
  loadBalancer: {}
