apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxdep
  name: nginxdep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxdep
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxdep
    spec:
      containers:
      - image: spurin/nginx-debug
        name: nginx-debug
        ports:
        - containerPort: 80
        resources: {}
status: {}
