apiVersion: v1
kind: Service
metadata:
  labels:
    app: myextnamesvc
  name: myextnamesvc
spec:
  externalName: nginxredcip.default.svc.cluster.local
  selector:
    app: myextnamesvc
  type: ExternalName
status:
  loadBalancer: {}
