apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxredextname
  name: nginxredextname
spec:
  externalName: nginxredcip.default.svc.cluster.local
  selector:
    app: nginxredextname
  type: ExternalName
status:
  loadBalancer: {}
