apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxblueextname
  name: nginxblueextname
spec:
  externalName: nginxbluecip.default.svc.cluster.local
  selector:
    app: nginxblueextname
  type: ExternalName
status:
  loadBalancer: {}
