apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/cronjob-scheduled-timestamp: "2026-02-14T14:34:00Z"
  creationTimestamp: "2026-02-14T14:34:00Z"
  generation: 1
  labels:
    batch.kubernetes.io/controller-uid: 8395e69f-d7d5-4d67-8145-9e42c370345e
    batch.kubernetes.io/job-name: sleep5-29517994
    controller-uid: 8395e69f-d7d5-4d67-8145-9e42c370345e
    job-name: sleep5-29517994
  name: sleep5-29517994
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: sleep5
    uid: 1a8efe27-22c3-48e7-860a-8d2719f1e769
  resourceVersion: "12165"
  uid: 8395e69f-d7d5-4d67-8145-9e42c370345e
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 5
  manualSelector: false
  parallelism: 3
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 8395e69f-d7d5-4d67-8145-9e42c370345e
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/controller-uid: 8395e69f-d7d5-4d67-8145-9e42c370345e
        batch.kubernetes.io/job-name: sleep5-29517994
        controller-uid: 8395e69f-d7d5-4d67-8145-9e42c370345e
        job-name: sleep5-29517994
    spec:
      containers:
      - command:
        - sleep
        - "5"
        image: ubuntu
        imagePullPolicy: Always
        name: sleep5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2026-02-14T14:34:18Z"
  conditions:
  - lastProbeTime: "2026-02-14T14:34:18Z"
    lastTransitionTime: "2026-02-14T14:34:18Z"
    message: Reached expected number of succeeded pods
    reason: CompletionsReached
    status: "True"
    type: SuccessCriteriaMet
  - lastProbeTime: "2026-02-14T14:34:18Z"
    lastTransitionTime: "2026-02-14T14:34:18Z"
    message: Reached expected number of succeeded pods
    reason: CompletionsReached
    status: "True"
    type: Complete
  ready: 0
  startTime: "2026-02-14T14:34:00Z"
  succeeded: 5
  terminating: 0
  uncountedTerminatedPods: {}
