apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curlpod
  name: curlpod
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep infinity
    image: curlimages/curl
    name: curlpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
