addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.2.3
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: klc-worker2
  targetRef:
    kind: Pod
    name: nginxsts-3
    namespace: default
    uid: c40db3ec-850c-4471-8272-0038b0f6439c
- addresses:
  - 10.244.2.2
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: klc-worker2
  targetRef:
    kind: Pod
    name: nginxsts-1
    namespace: default
    uid: 4461ebb2-774d-449b-b778-009381ee14d9
- addresses:
  - 10.244.1.3
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: klc-worker
  targetRef:
    kind: Pod
    name: nginxsts-2
    namespace: default
    uid: 1c67dec8-64d6-4ce2-b797-ad8d536b4764
- addresses:
  - 10.244.1.2
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: klc-worker
  targetRef:
    kind: Pod
    name: nginxsts-0
    namespace: default
    uid: 743a8f4d-1d78-4541-babf-e022b30a23be
- addresses:
  - 10.244.1.4
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: klc-worker
  targetRef:
    kind: Pod
    name: nginxsts-4
    namespace: default
    uid: 2ae2b00f-bfb2-4ea3-bb8a-b55e4519c730
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2026-02-17T02:27:17Z"
  creationTimestamp: "2026-02-17T02:27:17Z"
  generateName: nginxsts-
  generation: 1
  labels:
    app: nginxsts
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: nginxsts
    service.kubernetes.io/headless: ""
  name: nginxsts-42hql
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: nginxsts
    uid: 0172ae07-609d-451f-ae36-6b48b45a62e9
  resourceVersion: "57786"
  uid: a7e0bd35-e3dd-44b5-800f-4fad4b9d6974
ports: null
