apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"nginxsts"},"name":"nginxsts","namespace":"default"},"spec":{"replicas":5,"selector":{"matchLabels":{"app":"nginxsts"}},"serviceName":"nginxsts","template":{"metadata":{"labels":{"app":"nginxsts"}},"spec":{"containers":[{"image":"nginx","name":"nginx"}]}}}}
    creationTimestamp: "2026-02-17T02:55:00Z"
    generation: 1
    labels:
      app: nginxsts
    name: nginxsts
    namespace: default
    resourceVersion: "60425"
    uid: a6c52157-e4a1-43f1-90e2-e93b56cd3cfc
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 5
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nginxsts
    serviceName: nginxsts
    template:
      metadata:
        labels:
          app: nginxsts
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        partition: 1
      type: RollingUpdate
  status:
    availableReplicas: 5
    collisionCount: 0
    currentReplicas: 5
    currentRevision: nginxsts-644b8794c5
    observedGeneration: 1
    readyReplicas: 5
    replicas: 5
    updateRevision: nginxsts-644b8794c5
    updatedReplicas: 5
kind: List
metadata:
  resourceVersion: ""
