apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginxpod
  name: nginxcip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginxpod
status:
  loadBalancer: {}
