apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
    color: red
  name: ubuntupod-red
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
    color: green
  name: ubuntupod-green
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
    color: blue
  name: ubuntupod-blue
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
    color: red
  name: ubuntupod-red2
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
